PS1='\l:\H:\w # '
if [ -x /bin/hostname ] ; then
  PS1='\l:$(/bin/hostname 2>/dev/null):\w # '
fi
alias ll="ls -l"
alias la="ls -la"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
