#!/bin/sh

PATH="/sbin:/bin:/usr/bin:/usr/sbin:/lbin"

# disable hotplug helper, udevd listens to netlink
echo "" > /proc/sys/kernel/hotplug

# create min devices
# ########
#   Note: this is different from the usual 'cp -a'!
# ######## 
/lbin/cp -a /lib/udev/devices /dev

# start udevd
echo -n "Starting udevd "
udevd --daemon

# cleanup some stuff
rm -f /var/run/sysconfig/network

# unlikely, but we may be faster than the first event
mkdir /dev/.udev
mkdir /dev/.udev/queue

# create devices
/usr/bin/udevadm trigger

# 10 min - just long enough
/usr/bin/udevadm settle --timeout=100

echo "Mounting rpc_pipefs on /var/lib/nfs/rpc_pipefs"
mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs
echo "Starting /usr/sbin/rpc.idmapd"
/usr/sbin/rpc.idmapd < /dev/null
