#!/bin/sh

PATH="/sbin:/bin:/lbin"

# disable hotplug helper, udevd listens to netlink
echo "" > /proc/sys/kernel/hotplug

# create min devices
# ########
#   Note: this is different from the usual 'cp -a'!
# ######## 
/lbin/cp -a /lib/udev/devices /dev

# start udevd
echo -n "Starting udevd "
udevd --daemon

# cleanup some stuff
rm -f /var/run/sysconfig/network

# unlikely, but we may be faster than the first event
mkdir /dev/.udev
mkdir /dev/.udev/queue

# create devices
/sbin/udevtrigger

# until we know how to do better, just wait for _all_ events to finish
#loop=300
while test -d /dev/.udev/queue; do
    sleep 0.1;
#    test "$loop" -gt 0 || break
#    loop=$(($loop - 1))
done

