#! /usr/bin/perl

$part = shift;

@f = (<>);

if($part) {
  for (@f) {
    @i = split;
    if($i[0] eq $part) {
      $mp = $i[1];
      $_ = "$i[0] $i[1] $i[2] defaults $i[4] $i[5]\n";
      last;
    }
  }

  die "oops2\n" unless $mp;

  for (@f) {
    if(s#^/host/#$mp/#) {
      push @g, $_;
      undef $_;
    }
  }
}

for (@f, @g) {
  next unless $_;
  @i = split;
  printf "%s\t%s\t%s\t%s %s %s\n", @i unless exists $entry{$i[0]};
  $entry{$i[0]} = 1;
}

