#! /bin/bash

# for all missing files, create a link to /S.u.S.E.
# (_NOT_ recursive)
function mk_links {
  for i in "$@" ; do
    [ -d "$i" ] || continue
    [ -d "/S.u.S.E./$i" ] || continue
    j=`( cd /S.u.S.E./$i && echo * )`
    p=`( cd /S.u.S.E./$i && pwd )`
    [ "$j" ] || continue
    for k in $j ; do
      if [ $k != TRANS.TBL -a $k != rr_moved -a $k != links.tgz ] ; then
        if [ \( -e "$p/$k" -o -L "$p/$k" \) -a ! -e "$i/$k" ] ; then
          if [ -L "$p/$k" ] ; then
            ( cd $i && cp -a "$p/$k" . )
          else
            ( cd $i && ln -snf "$p/$k" . )
          fi
        fi
      fi
    done
  done
}


# copy all args from /S.u.S.E.
# (_recursive_)
function add_to_root {
  while [ "$1" ] ; do
    [ -e "/S.u.S.E./$1" ] || {
      shift ; continue
    }
    f=`( cd /S.u.S.E. && echo ./$1 )`
    [ "$f" ] || {
      shift
      continue
    }
    for i in $f ; do
      if [ -d /S.u.S.E./$i ] ; then
        if [ ! -d "/$i" -o -L "/$i" ] ; then
          rm -f /$i && mkdir /$i
        fi
        if [ -d "/$i" ] ; then
          if [ "`echo /S.u.S.E./$i/*`" != "/S.u.S.E./$i/*" ] ; then
            rm -rf /$i ; mkdir /$i
            cp -af /S.u.S.E./$i/* /$i
          fi
        fi
        chown --reference /S.u.S.E./$i /$i 2>/dev/null
        chmod --reference /S.u.S.E./$i /$i
      else
        rm -f /$i && cp -af /S.u.S.E./$i /$i
      fi
    done
    shift
  done
}


# make a local copy of a directory, everything in dir gets linked
# stops at the first non-existent argument
# usage: link_dir [--recursive [max_depth]] dir1 ...
function link_dir {
  local i r

  if [ "$1" = --recursive ] ; then
    shift
    if [ "$1" -ge 0 -o "$1" -lt 0 ] 2>/dev/null ; then
      r="$1"
      shift
    else
      r=1111
    fi
  else
    r=0
  fi

  while [ "$1" ] ; do
    if [ -d "/S.u.S.E./$1"  -a ! -L "/S.u.S.E./$1" ] ; then
      if [ -L "$1" -o ! -d "$1" ] ; then
        rm -f "$1"
        mkdir "$1"
        chown --reference /S.u.S.E./$1 $1 2>/dev/null
        chmod --reference /S.u.S.E./$1 $1
      fi
      mk_links "$1"
      if [ "$r" -ge 1 ] ; then
        for i in $1/* ; do
          [ -d $i ] && link_dir --recursive $((r-1)) $i
        done
      fi
    else
      return 1
    fi
    shift
  done

  return 0
}

cd /

if [ "$1" = "--link_dir"  -o "$1" = "-l" ] ; then
  shift
  link_dir "$@"
  exit
fi

if [ "$1" = --add_to_root -o "$1" = "-a" ] ; then
  shift
  add_to_root "$@"
  exit
fi

