#! /bin/sh

PATH=$PATH:/S.u.S.E./bin:S.u.S.E./usr/bin
cd /

if [ -f /etc/liveeval.conf ] ; then
  . /etc/liveeval.conf
else
  exit 1
fi

debug=
nodisk=
x=",$live,"
[ "$x" != "${x/,debug,}" ] && debug=1

partition=
[ "$l_nodisk" ] && nodisk=1
[ "$l_partition" ] && partition=/dev/$l_partition


[ "$debug" ] && echo $LINENO && /bin/bash

if [ ! -d /S.u.S.E./etc ] ; then
  # mount Live CD
  mount -n /S.u.S.E.
fi

[ -d /.livecd/locale ] && export TEXTDOMAINDIR=/.livecd/locale
export TEXTDOMAIN=livecd
if [ -f /etc/sysconfig/language ] ; then
  . /etc/sysconfig/language
fi

LANG=$RC_LANG gettext -n -s "Saving LiveEval CD changes"

[ "$debug" ] && echo $LINENO && /bin/bash

if [ ! "$nodisk" ]; then
  echo
  printf "`LANG=$RC_LANG gettext 'Writing LiveEval config'`"
  echo

  error=
  mount -n $partition /mnt || error=21

  if [ ! "$error" ] ; then
    cd /
    tar -zclf /mnt/$liveconfig . 2>/dev/null || error=1
  fi

  if [ "$error" ] ; then
    printf "`LANG=$RC_LANG gettext 'An error occurred while writing %s.'`" "$liveconfig"
    echo
    LANG=$RC_LANG gettext -s "Sorry, your LiveEval CD changes might be lost. :-("
  fi

  umount -n /mnt
fi

[ "$debug" ] && echo $LINENO && /bin/bash

umount -n /S.u.S.E.
# umount Live CD

[ "$debug" ] && echo $LINENO && /bin/bash

exit 0
