#! /bin/sh

[ -e /etc/.SuSEok ] && exit 0

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/S.u.S.E./bin
cd /

preserve=`echo /sbin/{init,live-setup} /bin/bash\
  /lib/lib{c.so.6,dl.so.2,ncurses.so.5.0,history.so.4.1,readline.so.4.1}\
  /lib/ld-2.1.3.so\
  /etc/{.SuSEfiles,mtab} /tmp`

echo -n "Integrating Live CD"

nodisk=
[ "$live" = nodisk ] && nodisk=1

mount /S.u.S.E.

rm -rf /lib/modules

ln -snf /S.u.S.E./var/lib/rpm /var/lib

rm -f /var/X11R6/lib ; mkdir /var/X11R6/lib

/sbin/mk_links . bin etc lib sbin var/X11R6/sax var/X11R6/sax/config var/lib/apsfilter\
  opt opt/kde opt/kde/share var/X11R6/xfine\
  sbin/init.d sbin/conf.d etc/pcmcia etc/httpd\
  var/X11R6/lib

rm -f usr           ; mkdir usr           ; /sbin/mk_links usr
rm -f usr/X11R6     ; mkdir usr/X11R6     ; /sbin/mk_links usr/X11R6
rm -f usr/X11R6/bin ; mkdir usr/X11R6/bin ; /sbin/mk_links usr/X11R6/bin

if [ -d etc/X11 -a ! -L etc/X11 ] ; then
  /sbin/mk_links etc/X11
fi

if [ ! -x /bin/y2qt ] ; then
  ln -s y2bignfat /bin/y2qt
fi

if [ ! "$nodisk" ] ; then
  /sbin/mk_links sbin/init.d/rc?.d
fi

cp -af /S.u.S.E./etc/pam.d/* /etc/pam.d
rm -f /etc/pam.d/TRANS.TBL
cp -af /S.u.S.E./etc/rc.config /etc
cp -af /S.u.S.E./var/X11R6/sax/config/saxrc /var/X11R6/sax/config
cp -af /S.u.S.E./opt/kde/share/config/* /opt/kde/share/config
rm -f /opt/kde/share/config/TRANS.TBL
cp -af /S.u.S.E./etc/SuSEconfig /etc
rm -f /etc/SuSEconfig/TRANS.TBL
cp -af /S.u.S.E./sbin/init.d/{boot,halt}.local /sbin/init.d
cp -af /S.u.S.E./etc/{passwd,group,shadow,gshadow,nsswitch.conf} /etc
cp -af /S.u.S.E./etc/httpd/httpd.conf /etc/httpd
cp -af /S.u.S.E./etc/wvdial.conf /etc
cp -af /S.u.S.E./etc/ppp/* /etc/ppp
cp -af /S.u.S.E./etc/isdn/* /etc/isdn
cp -af /S.u.S.E./etc/vbox/* /etc/vbox
cp -af /S.u.S.E./etc/rc.config.d/* /etc/rc.config.d
rm -f /etc/{ppp,isdn,vbox,rc.config.d}/TRANS.TBL
cp -af /S.u.S.E./var/X11R6/lib/sax /var/X11R6/lib
rm -f /var/X11R6/lib/xfine ; mkdir /var/X11R6/lib/xfine
cp -af /S.u.S.E./etc/suse-blinux.conf /etc
cp -af /S.u.S.E./var/lib/{YaST,codadmin,dhcp,jove,ldap,minicom,pcmcia,svgatext,wvdial,xdm,zope} /var/lib
mkdir -p /var/lib/dosemu/drives
/sbin/mk_links var/lib/dosemu var/lib/dosemu/drives
rm -f `find /var/lib -name TRANS.TBL`

rm -f /etc/conf.modules
touch -r /lib/modules/`uname -r`/modules.dep /etc/modules.conf

perl -pi -e 's/-(?=FollowSymLinks)//g' /etc/httpd/httpd.conf

perl -pi -e 's/^(FQHOSTNAME=).*/$1\"suse\"/' /etc/rc.config
perl -pi -e 's/^(SUSEWM_UPDATE=).*/$1\"no\"/' /etc/rc.config
rm -f /sbin/conf.d/SuSEconfig.{perl,groff}

perl -pi -e 's/^(Sourcemounted:).*/$1 1/' /etc/install.inf

if [ -f /etc/install.inf ] ; then
  echo
  mount -n -t proc proc /proc
  /usr/sbin/hwinfo --special=braille 2>>/etc/install.inf
  umount /proc
fi

if [ -f /etc/install.inf ] ; then
#  eval `grep ': ' /etc/install.inf | sed -e 's/:  */="/' -e 's/$/"/' -e 's/^/export /'`
  eval $(grep ': ' /etc/install.inf | sed -e 's/"/"\\""/g' -e 's/:  */="/' -e 's/$/"/' -e 's/^/export /')
fi

if [ "$Language" ] ; then
  perl -pi -e 's/^(LANGUAGE=).*/$1\"'"$Language"'\"/' /etc/rc.config
  perl -pi -e 'if(/unset LANG/) { $_ = "    export LANG=\"'"$Language"'\"\n" if $a++ }' /etc/SuSEconfig/profile
  perl -pi -e 'if(/unsetenv LANG/) { $_ = "    setenv LANG \"'"$Language"'\"\n" if $a++ }' /etc/SuSEconfig/csh.cshrc
fi

if [ "$Keytable" ] ; then
  perl -pi -e 's/^(KEYTABLE=).*/$1\"'"$Keytable"'\"/' /etc/rc.config
fi

#if [ "$Nameserver" ] ; then
#  echo "nameserver $Nameserver" >>/etc/resolv.conf
#fi

if [ "$Braille" ] ; then
  sed -e "s#brlname=.*#brlname=$Braille#" -e "s#brlport=.*#brlport=$Brailledevice#" /etc/suse-blinux.conf >/tmp/suse-blinux.conf
  mv -f /tmp/suse-blinux.conf /etc
  /etc/rc.d/suse-blinux start
  umount /proc 2>/dev/null
else
  rm -f /etc/rc.d/rc?.d/*suse-blinux
fi

part=
touch /etc/SuSElive
if [ "$Disks" -a ! "$nodisk" ]; then
  mount -n -t proc proc /proc
  cat /proc/mounts >/etc/mtab
  /sbin/find_config $Disks >/etc/SuSElive
  umount /proc
  . /etc/SuSElive
fi

newhome=
nonewuser=
error=
udated=
if [ "$part" ]; then
  i=
  [ "$dosdrive" ] && i="$dosdrive, "

  echo
  echo "Using "\""suselive.700"\"" on $part ($i$fstype, $partsize MB) to store data"

  mkdir /host || error=20
  mount $part /host || error=21
  if [ "$error" = "" -a "$suseimg" -a -f /host/$suseimg -a "$live" != "new" ] ; then
    echo "Updating filesystem."
    cp -a /etc/SuSElive /tmp
    chattr +i $preserve
    tar -zxpf /host/$suseimg 2>/dev/null
    chattr -i $preserve
    touch -r /lib/modules/`uname -r`/modules.dep /etc/modules.conf
    rm -rf /home/tmp ; mkdir -p /home/tmp ; chmod 1777 /home/tmp
    rm -rf /tmp ; ln -s /home/tmp /
    updated=1
    nonewuser=1
    grep -q -s "part=$part" /etc/SuSElive || cp -a /tmp/SuSElive /etc
    rm -f /tmp/SuSElive
    if [ -f /etc/.SuSErmlist ] ; then
      rm -rf `cat /etc/.SuSErmlist`
    fi
    rm -f /etc/.SuSErmlist
  else
    suseimg=suselive.700
    perl -pi -e 's/^(suseimg=).*/$1suselive.700/' /etc/SuSElive
  fi

  if [ ! "$error" ] ; then
    [ ! "$suseswap" ] && suseswap=suselive.swp
    [ ! "$susehome" ] && susehome=suselive.usr
    if [ "$swapsize" -a ! -f "/host/$suseswap" ] ; then
      echo "Creating swap file "\""suselive.swp"\"" ($swapsize MB)"
      dd if=/dev/zero of="/host/$suseswap" bs=1M count=$swapsize 2>/dev/null
      perl -pi -e 's/^(suseswap=).*/$1suselive.swp/' /etc/SuSElive
    fi
    if [ "$homesize" -a ! -f "/host/$susehome" ] ; then
      echo "Creating user data file "\""suselive.usr"\"" ($homesize MB)"
      dd if=/dev/zero of="/host/$susehome" bs=1M count=$homesize 2>/dev/null
      mke2fs -q -F -b 1024 -m 0 "/host/$susehome" 2>/dev/null
      tune2fs -i 0 "/host/$susehome" 2>/dev/null >/dev/null
      perl -pi -e 's/^(susehome=).*/$1suselive.usr/' /etc/SuSElive
      newhome=1
    fi
  fi
else
  if [ ! "$nodisk" ] ; then
    echo
    echo -e "\aFound no usable partition. Your data will NOT be saved to disk."
    sleep 10
    error=99
  fi
fi

if [ ! "$nodisk" ] ; then
  if [ "$error" ] ; then
    perl -pi -e 's/^(suseimg=).*/$1/; s/^(suseswap=).*/$1/; s/^(susehome=).*/$1/' /etc/SuSElive
  fi
  . /etc/SuSElive
fi

if [ ! "$updated" ] ; then
  if [ "$suseswap" ] ; then
    echo "Activating swap space"
    grep -q -s "$suseswap" /etc/fstab || {
      echo "/host/$suseswap swap swap defaults 0 0" >>/etc/fstab
    }
  fi

  if [ "$susehome" ] ; then
    echo "Activating /home"
    grep -q -s "$susehome" /etc/fstab || {
      echo "/host/$susehome /home ext2 defaults,loop=/dev/loop1 0 0" >>/etc/fstab
    }
  fi
fi

if [ ! "$nodisk" ] ; then
  if [ ! "$updated" ] ; then
    mount /proc
    rmdir /mnt ; ln -s / /mnt
    cp /etc/fstab /tmp/fstab.save
    if [ "$suseswap" ] ; then
      mkswap /host/$suseswap >/dev/null
    fi
    swapon -a
    if [ "$susehome" ] ; then
      mount /home
      rm -rf /home/tmp ; mkdir /home/tmp ; chmod 1777 /home/tmp
    fi
    /usr/sbin/syslogd
    [ "$livetest" ] && /bin/bash
    # to be compatible with 6.4
    if [ -x /usr/lib/YaST2/bin/YaST2.start ] ; then
      /usr/lib/YaST2/bin/YaST2.start
    else
      /lib/YaST2/bin/YaST2.start
    fi
    killall syslogd
    rm -f /var/lib/YaST2
    rm -f /mnt ; mkdir /mnt
    cmp -s /etc/fstab /tmp/fstab.save || {
      grep -v /proc /etc/fstab >>/tmp/fstab.save
      mv /tmp/fstab.save /etc/fstab
    }
    if [ "$susehome" ] ; then
      umount /home
      losetup -d /dev/loop1
    fi
    swapoff -a 2>/dev/null
    umount /host 2>/dev/null
    rmdir /host 2>/dev/null
    if [ "$part" ] ; then
      fix_fstab $part </etc/fstab >/etc/fstab_
      mv /etc/fstab_ /etc/fstab
    fi
    cp /proc/mounts /etc/mtab
    if [ "$susehome" ] ; then
      rm -rf /tmp ; ln -s /home/tmp /
    fi
    mount $part
    [ "$livetest" ] && /bin/bash
    umount /proc
  else
    if [ "$suseswap" ] ; then
      mkswap /host/$suseswap >/dev/null
    fi
    umount /host 2>/dev/null
    rmdir /host 2>/dev/null
    if [ "$suseswap" -o "$susehome" ] ; then
      mount $part
      if [ "$susehome" ] ; then
        mount /home
        rm -rf /home/tmp ; mkdir /home/tmp ; chmod 1777 /home/tmp
        umount /home
      fi
    fi
    [ "$livetest" ] && /bin/bash
  fi
fi

if [ "$Braille" -a -x /etc/rc.d/suse-blinux ] ; then
  /etc/rc.d/suse-blinux stop
  umount /proc 2>/dev/null
fi

if [ "$umount" != no ] ; then
  umount /S.u.S.E.
else
  echo "/S.u.S.E not unmounted"
fi

echo -e "\033[71G\033[32mdone\033[m"

[ "$livetest" ] ||  rm -f /sbin/{find_config,fix_fstab}
if [ "$nodisk" ] ; then
  rm -f /sbin/live-shutdown /etc/.SuSEfiles
fi
rm -f /sbin/live-setup ; exec /sbin/init
