#! /bin/sh

debug=

PATH=$PATH:/S.u.S.E./bin:S.u.S.E./usr/bin
cd /

[ "$debug" ] && echo $LINENO && /bin/bash

if [ ! -d /S.u.S.E./etc ] ; then
  # mount Live CD
  mount -n /S.u.S.E.
fi

if [ -f /etc/install.inf ]; then
  eval `grep ': ' /etc/install.inf | sed -e 's/:  */="/' -e 's/$/"/' -e 's/^/export /'`
fi

if [ -f /etc/SuSElive ] ; then
  . /etc/SuSElive
else
  exit 1
fi

[ "$debug" ] && echo $LINENO && /bin/bash

if [ "$part" -a "$suseimg" ]; then
  i=
  [ "$dosdrive" ] && i="$dosdrive, "
  echo
  echo "Writing info to $suseimg on $part ($i$fstype, $partsize MB)"

  mount -n $part /mnt || error=21

  if [ "$error" = "" -a "$suseimg" ] ; then
    if [ -f /etc/.SuSEfiles ] ; then
      mount -n -oremount,rw /
      rm -f /etc/.SuSErmlist
      for i in `cat /etc/.SuSEfiles` ; do
        if [ ! -e "$i" -a ! -L "$i" ] ; then
          echo "$i" >>/etc/.SuSErmlist
        fi
      done
      mount -n -oremount,ro /
    fi
    tar --exclude /dev/console -zclf /mnt/$suseimg / 2>/dev/null || error=1
  fi

  if [ ! -f /mnt/suselive.txt ] ; then
    echo -e "$suseimg contains data for your SuSE Linux 8.0 Evaluation CD.\r" >/mnt/suselive.txt
    echo -e "suselive.swp (if it exists) is the swap file.\r" >>/mnt/suselive.txt
    echo -e "suselive.usr (if it exists) is an ext2 file system with the user's home dir.\r" >>/mnt/suselive.txt
  fi

  if [ "$error" ] ; then
    echo "An error occurred while writing $suseimg."
    echo "Sorry, your latest Live CD changes might be lost. :-("
  fi

  umount -n /mnt
fi

[ "$debug" ] && echo $LINENO && /bin/bash

umount -n /S.u.S.E.
# umount Live CD

[ "$debug" ] && echo $LINENO && /bin/bash

exit 0
