#! /bin/bash

root=/S.u.S.E.

for i in "$@" ; do
#  echo \>\>$i
  j=`( cd $root/$i; echo * )`
  p=`( cd $root/$i; pwd )`
  for k in $j ; do
    if [ $k != TRANS.TBL -a $k != rr_moved -a $k != links.tgz ] ; then
#      echo $k
      if [ -e "$p/$k" -a ! -e "$i/$k" ] ; then
#        echo "$p/$k"
        if [ -L "$p/$k" ] ; then
          ( cd $i; cp -a "$p/$k" . )
        else
          ( cd $i; ln -snf "$p/$k" . )
        fi
      fi
    fi
  done
done

