#! /bin/bash

exec >&2

# dummy definition to make parse-zdev.sh happy
# 'rd.zdev=no-auto' case is handled in linuxrc
getargs () { true ; }

# s390x: I/O device pre-configuration (jsc#SLE-7396, bsc#1198326)
if [ -x /usr/lib/dracut/modules.d/95zdev/parse-zdev.sh ] ; then
  . /usr/lib/dracut/modules.d/95zdev/parse-zdev.sh
fi
