#! /bin/bash

exec >&2

chmod 700 /root/.gnupg

if [ -d /usr/lib/rpm/gnupg/keys ] ; then
  touch /installkey.gpg
  gpg --batch --homedir /root/.gnupg --no-default-keyring --ignore-time-conflict --ignore-valid-from --keyring /installkey.gpg --import /usr/lib/rpm/gnupg/keys/*
elif [ -f /usr/lib/rpm/gnupg/suse-build-key.gpg ] ; then
  cp /usr/lib/rpm/gnupg/suse-build-key.gpg /installkey.gpg
fi

if [ ! -s /installkey.gpg ] ; then
  echo "warning: no build keys!"
fi

# needed for nfs
echo "Mounting rpc_pipefs on /var/lib/nfs/rpc_pipefs"
mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs

if [ -x /usr/sbin/rpc.idmapd ] ; then
  echo "Starting rpc.idmapd"
  /usr/sbin/rpc.idmapd < /dev/null
fi

if [ -x /bin/dbus-daemon ] ; then
  echo "Starting dbus-daemon"
  /bin/dbus-uuidgen --ensure
  /bin/dbus-daemon --system
fi

if [ -x usr/sbin/wickedd ] ; then
  echo "Starting wicked"
  {
    /usr/sbin/wickedd
    for i in /usr/lib/wicked/bin/wickedd-* ; do $i ; done
  } >/var/log/wickedd.log 2>&1
fi

