#! /bin/sh

# ensure some trees are completely writable
for i in /etc /media /root /run /var ; do
  cp -aL $i ${i}_tmp
  rm -rf $i
  mv ${i}_tmp $i
done

if [ -f /mounts/initrd/etc/suse-blinux.conf ] ; then
  grep -q '^brlname=none' /mounts/initrd/etc/suse-blinux.conf || {
    cp /mounts/initrd/etc/suse-blinux.conf /etc
    insserv brld
    insserv sbl
  }
fi

# keep some initrd config files for rescue system
for i in etc/modprobe.d/blacklist etc/modprobe.d/noload ; do
  [ -f /mounts/initrd/$i ] && cp -f /mounts/initrd/$i /$i
done

# bash >/dev/console 2>&1

rm -f /mounts/initrd/{*,.*}
rmdir /mounts/initrd/* 2>/dev/null
rm -rf /mounts/initrd/{bin,download,etc,lbin,lib,modules,oldroot,root,sbin,scripts,tmp,usr,var}

