#! /bin/sh

# ensure some trees are completely writable
for i in /etc /media /root /run /var ; do
  cp -aL $i ${i}_tmp
  rm -rf $i
  mv ${i}_tmp $i
  ln -snf /proc/self/mounts /etc/mtab
done

if [ -f /mounts/initrd/etc/suse-blinux.conf ] ; then
  grep -q '^brlname=none' /mounts/initrd/etc/suse-blinux.conf || {
    cp /mounts/initrd/etc/suse-blinux.conf /etc
    insserv brld
    insserv sbl
  }
fi

# keep some initrd config files for rescue system
cd /mounts/initrd
for i in etc/modprobe.d/blacklist etc/modprobe.d/noload etc/resolv.conf etc/sysconfig/network/* ; do
  [ -f "$i" ] && cp -f "$i" "/$i"
done
cd /

# bash >/dev/console 2>&1

rm -f /mounts/initrd/{*,.*}
rmdir /mounts/initrd/* 2>/dev/null
rm -rf /mounts/initrd/{bin,download,etc,lbin,lib,modules,oldroot,root,sbin,scripts,tmp,usr,var}

