#! /bin/bash
#USAGE: requires the LOGHOST variable to be set

[ -n "$LOGHOST" ] || exit 0

if [[ ! "$LOGHOST" =~ :[0-9]+$ ]]; then
	LOGHOST="$LOGHOST:514"
fi

#set loghost
echo "*.*@${LOGHOST}" > /etc/rsyslog.d/loghost.conf

echo -n "starting rsyslogd (logging to /var/log/messages)..."
if /usr/sbin/rsyslogd ; then
  echo " ok"
else
  echo " failed"
fi
