#! /bin/bash

exec >&2

PATH="/sbin:/bin:/usr/bin:/usr/sbin:/lbin"

# load some modules before udevd
for i in edd scsi_dh_alua scsi_dh_emc scsi_dh_rdac ; do
  [ -f /modules/$i.ko ] && modprobe $i
done

# disable hotplug helper, udevd listens to netlink
echo "" > /proc/sys/kernel/hotplug

# start udevd
echo -n "Starting udevd "
if [ -n "$linuxrc_debug" ] ; then
  udevd --daemon --debug 2>/var/log/udev.log
else
  udevd --daemon
fi

# create devices (cf. bsc#1084357)
/usr/bin/udevadm trigger --type=subsystems --action=add
/usr/bin/udevadm trigger --type=devices --action=add

# 10 min - just long enough
/usr/bin/udevadm settle --timeout=100

