#! /bin/sh

# zram size is passed as first argument
size=$1

PATH=/usr/bin:/usr/sbin:/bin:/sbin

# no modprobe
for i in 842_decompress 842_compress lz4_compress lz4hc_compress zram jbd2 mbcache crc16 ext4 ; do
  for ext in .ko .ko.xz .ko.zst ; do
    m=/modules/$i$ext
    [ -f $m ] && insmod $m
  done
done

echo zstd > /sys/block/zram0/comp_algorithm
echo $size > /sys/block/zram0/disksize

mkfs.ext2 -q /dev/zram0
