#! /bin/sh

yast="$1"
shift

exec 2>&1
stty sane

echo -en \\033c

# linuxrc passes the root directory of the freshly mounted instsys in
# the environment variable INSTSYS.
#
# create symlinks for all missing files
conservative_lndir "$INSTSYS" "/"

# start syslog (messages are logged to /dev/tty4)
[ -x /sbin/syslogd ] && /sbin/syslogd

# create a new modules.dep
#
# modules from initrd (in /modules) are preferred over those from CD (below
# /lib/modules)
#
rm -f /etc/modules.conf
cp "$INSTSYS/etc/modules.conf" /etc
cat >>/etc/modules.conf <<xxx
path=/modules
path=/lib/modules/`uname -r`
depfile=/etc/modules.dep
generic_stringfile=/etc/modules.generic_string
pcimapfile=/etc/modules.pcimap
isapnpmapfile=/etc/modules.isapnpmap
usbmapfile=/etc/modules.usbmap
parportmapfile=/etc/modules.parportmap
xxx
depmod -a 2>/dev/null

# start sshd
arch=$(uname -m)
case "$arch" in
    s390|s390x) ;;
    *)
	# start sshd 
	if [ -x /usr/sbin/sshd ] && \
          grep -vq ' nossh' /proc/cmdline && \
          grep -q 'Bootmode:.*Net' /etc/install.inf ; then
	    SSH_FAILED=
	    echo 'sshd found, prepare remote login'
	    rm -rf /etc/ssh /root /etc/shadow
	    mkdir -p /root/.ssh
	    cp -a $INSTSYS/root/.ssh/* /root/.ssh
	    cp -a $INSTSYS/root/.bash_login /root
	    cp -a $INSTSYS/root/.vimrc /root
	    cp -a $INSTSYS/etc/shadow /etc
	    cp -a $INSTSYS/etc/ssh /etc
            chmod -R og-rxw  /etc/ssh /root /etc/shadow 2>/dev/null
	    chown -R 0.0  /etc/ssh /root /etc/shadow 2>/dev/null
	    # echo "nameserver 10.10.0.1" > /etc/resolv.conf
	    # echo "nameserver 10.10.11.1" >> /etc/resolv.conf
	    # echo "search suse.de" >> /etc/resolv.conf
	    mkdir -p /dev/pts
	    mkdir -p /dev/shm
	    grep -q devpts /proc/mounts || \
                mount -n -t devpts -o mode=0620,gid=5 devpts /dev/pts
	    /usr/sbin/sshd || {
	        export SSH_FAILED=true
	        echo 'sshd did NOT start!'
	    }
	    if [ ! "$SSH_FAILED" ] ; then
	        echo
	        echo /sbin/ifconfig `grep eth /proc/net/dev | cut -f 1 -d : `
	        for i in  `grep eth /proc/net/dev | cut -f 1 -d : ` ; do
		    /sbin/ifconfig $i | grep UP > /dev/null 2>&1 && /sbin/ifconfig $i | head -n 2
	        done
                cat <<xxx

      ***  sshd has been started  ***

  This is only done during beta tests.
  It is NOT a feature of the final release.

  If you don't want sshd to be started, use
  the 'nosshd' option at the boot promt.

  Press return to contiunue...
xxx
	        read
	    fi
	    export Y2DEBUG=1
        fi
        ;;
esac


# yast1 doesn't like it
rm -f /etc/fstab

# now, run yast
ec=
if [ "$yast" = yast1 ] ; then
    /sbin/yast "$@" ; ec=$?
fi

if [ "$yast" = yast2 ] ; then
    /usr/lib/YaST2/bin/YaST2.start "$@" ; ec=$?
fi

umount devpts 2>/dev/null

exit $ec
