#! /bin/sh

# Check if /dev/tty4 is available (might not be the case for installs via
# serial line).

rm -f /etc/syslog.conf
if ( test -c /dev/tty4 && > /dev/tty4 ) > /dev/null 2>&1 ; then
	cat <<-blub >>/etc/syslog.conf
	*.*			/dev/tty4
	blub
else
	cat <<-blub >>/etc/syslog.conf
	*.*			/dev/null
	blub
fi

exec /sbin/syslogd.bin
