#!/bin/sh
# IP_INTERFACE=ctc
# IP_ADDR=1.2.3.4
# IP_HOST=muell.schrott.de
# IP_GATEWAY=2.3.4.5
# IP_DNS=3.4.5.6
# IP_NETMASK=12.12.12.12
# IP_PEER=13.13.13.13
# DEVNO=600
# DEVNO2=500
# DEVNO3=4
# PORTNO=123
# PORTNAME=BLABLA
# INST_TYP=nfs
# INST_IP_ADDR=40.40.40.40
# INST_IP_DIR=/s390
# INST_SCREEN=X
# INST_X_ADDR=50.50.50.50
# INST_PASSWORD
# VNC_PASSWORD
#
#	Check the parameter for kompleetness
#
PARAM_VALID=yes
CONFIG_IS_OK=1
VALID_INTERFACES="c7000 c7000p ctc escon qeth lcs tr iucv hsi"
#
#	Test IP_ADDR, IP_HOST, IP_GATEWAY, IP_DNS
#
#
# checks numbers between 0 and 65535:
#
# example:
# if echo $NUMBER | check_number; then ...
#
function check_number()
{
        IFS=". " read n1 n2 n3 n4 n5 rest
        for i in n1 n2 n3 n4 n5 
        do
		eval x=\$$i
		[ "$x" = "" ] && continue
		if [ "$x" -lt 0 -o "$x" -gt 65535 ]; then
			echo "$x: Value must be between 0 and 65535"
			return 1
		fi
        done
        return 0
}
#
# checks an IP to have numbers only between 0 and 255:
#
# example:
# if echo $IP_ADDR | check_ip; then ...
#
function check_ip()
{
        IFS=". " read ip1 ip2 ip3 ip4 rest
        for i in ip1 ip2 ip3 ip4
        do
                eval x=\$$i
		[ "$x" = "" ] && return 1
                if [ "$x" -lt 0 -o "$x" -gt 255 ]; then
                        echo "$x: Value must be between 0 and 255"
                        return 1
                fi
        done
        return 0
}
#
#
#
case $IP_INTERFACE in
	tr| eth| qeth| c7000| hsi)
	[ -z "$IP_NETMASK" ] && CONFIG_IS_OK=0
	echo $IP_NETMASK | check_ip
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	;;
	ctc| escon| iucv)
	[ -z "$IP_PEER" ] && CONFIG_IS_OK=0
	echo $IP_PEER | check_ip
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	;;
esac
#
#	Test devno and the rest.
#
case $IP_INTERFACE in
	ctc|escon)
#		check READ_DEVNO, WRITE_DEVNO
	echo $READ_DEVNO $WRITE_DEVNO | check_number
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	;;
	qeth)
#		check READ_DEVNO, DATA_DEVNO, PORTNAME
	echo $READ_DEVNO $DATA_DEVNO | check_number
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	[ `expr "$PORTNAME" : "[A-Z1-0]" ` ] && CONFIG_IS_OK=0
	;;
	lcs|tr)
#		check DEVNO, PORTNO
	echo $DEVNO $PORTNO | check_number
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	;;
	hsi)
#		check READ_DEVNO, WRITE_DEVNO, DEVNO3
	echo $READ_DEVNO $WRITE_DEVNO $DEVNO3 | check_number
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	;;
	iucv)
#		check PEER
	echo $PEER | check_ip
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	;;
esac
#
#	Test Installparameters (nfs, Samba, ftp,http)
#
case $INST_TYP in
	nfs|samba|ftp|http)
	echo $INST_IP_ADDR | check_ip
	[ $? -eq 1 ] && CONFIG_IS_OK=0
	[ -z "$INST_IP_DIR" ] && CONFIG_IS_OK=0
	;;
	*)
	CONFIG_IS_OK=0
	;;
esac
#
[ "$INST_SCREEN" = "X" ] && {
echo "$INST_X_ADDR" | check_ip
[ $? -eq 1 ] && CONFIG_IS_OK=0
}
#
#
echo $CONFIG_IS_OK
