#!/bin/sh
#
#	Create interface
#	Create chandev-Entry
#
ROOT=$1
INSTALLINF=/etc/install.inf
CHANDEVCONF=$ROOT/etc/chandev.conf
DEVICEDIR=$ROOT/etc/sysconfig/network/
ROUTINGFILE=$ROOT/etc/sysconfig/network/routes
HOSTFILE=$ROOT/etc/HOSTNAME
RESFILE=$ROOT/etc/resolv.conf
CONFIGFILE=$ROOT/etc/sysconfig/network/config
CONFIGFILETMP=$ROOT/etc/sysconfig/network/config.tmp
# INSTALLINF=netsetup.inf
# INSTALLINF=install.inf
# CHANDEVCONF=chandev.conf
# DEVICEDIR=
# ROUTINGFILE=routes
#
#
if [ -f $INSTALLINF ]
then
#	Check for chandev
	CHANDEV=`grep Chandev: $INSTALLINF | uniq | sed -e 's/Chandev: \\(.*\\)/\\1/'`
	if [ ! -z "$CHANDEV" ]
	then
		echo $CHANDEV >> $CHANDEVCONF
	fi
#
#	Create interfacefile
#
	NETDEV=`grep Netdevice: $INSTALLINF | uniq | sed -e 's/Netdevice: \\(.*\\)/\\1/'`
	DEVICEFILE=${DEVICEDIR}ifcfg-$NETDEV
	echo "BOOTPROTO=\"static\"" > $DEVICEFILE
	echo "STARTMODE=\"onboot\"" >> $DEVICEFILE
	IP=`grep "^IP:" $INSTALLINF | uniq | sed -e 's/IP: \\(.*\\)/\\1/'`
	echo "IPADDR=\"$IP\"" >> $DEVICEFILE
#
#	Create pointopoint Interfaces
#
	PTOP=`grep Pointopoint: $INSTALLINF | uniq | sed -e 's/Pointopoint: \\(.*\\)/\\1/'`
	if [ ! -z "$PTOP" ]
	then
		echo "REMOTE_IPADDR=\"$PTOP\"" >> $DEVICEFILE
	fi
#
#	create broadcast-interface
#
	NWMASK=`grep Netmask: $INSTALLINF | uniq | sed -e 's/Netmask: \\(.*\\)/\\1/'`
	if [ ! -z "$NWMASK" ]
	then
		echo "NETMASK=\"$NWMASK\"" >> $DEVICEFILE
	fi
	NW=`grep Netmask: $INSTALLINF | uniq | sed -e 's/Netmask: \\(.*\\)/\\1/'`
	if [ ! -z "$NW" ]
	then
		echo "NETWORK=\"$NW\"" >> $DEVICEFILE
	fi
	NWBROADCAST=`grep Netmask: $INSTALLINF | uniq | sed -e 's/Netmask: \\(.*\\)/\\1/'`
	if [ ! -z "$NWBROADCAST" ]
	then
		echo "BROADCAST=\"$NWBROADCAST\"" >> $DEVICEFILE
	fi
#	
#	Create routingfile
#
	GW=`grep Gateway: $INSTALLINF | uniq | sed -e 's/Gateway: \\(.*\\)/\\1/'`
	if [ ! -z "$GW" ]
	then
		echo "default $GW 0.0.0.0 -" >> $ROUTINGFILE
	fi
#
#	Create /etc/HOSTNAME
#
	HOSTNAME=`grep Machinename: $INSTALLINF | uniq | sed -e 's/Machinename: \\(.*\\)/\\1/'`
	if [ ! -z "$HOSTNAME" ]
	then
		echo "$HOSTNAME" >> $HOSTFILE
	fi
#
#	Create /etc/resolv.conf
#
	DOMAIN=`grep Domain: $INSTALLINF | uniq | sed -e 's/Domain: \\(.*\\)/\\1/'`
	NAMESERVER=`grep Nameserver: $INSTALLINF | uniq | sed -e 's/Nameserver: \\(.*\\)/\\1/'`
	if [ ! -z "$DOMAIN" -a ! -z "$NAMESERVER" ]
	then
		echo "domain $DOMAIN" >> $RESFILE
		echo "nameserver $NAMESERVER" >> $RESFILE
	fi
	WAIT_FOR_INTERFACES=`grep WAIT_FOR_INTERFACES: $INSTALLINF | uniq | sed -e 's/WAIT_FOR_INTERFACES: \\(.*\\)/\\1/'`
	if [ ! -z "$WAIT_FOR_INTERFACES" ]
	then
#
#	WAIT_FOR_INTERFACES is not zero. Put the value into the file
#	We are the first to modify this file. Default is zero
#
		sed -n "s/^WAIT_FOR_INTERFACES=.*/WAIT_FOR_INTERFACES=$WAIT_FOR_INTERFACES/" < $CONFIGFILE > $CONFIGFILETMP
		[ $? -eq 0 ] && mv $CONFIGFILETMP $CONFIGFILE
	fi
fi
:
