#!/bin/sh
#
#	Ask the user for the installation-Source
#
: ${INST_INFO:=nothing}
: ${INST_IP_ADDR:=250.250.250.250}
: ${INST_IP_DIR:=empty}
: ${INST_SCREEN:=nothing}
: ${INST_X_ADDR:=251.251.251.251}
: ${VNC_PASSWORD:=1234}
ANSW=empty
#
#
#
# to preserve the script from doing anything real, call it with
# CONDOM=echo
: ${CONDOM:=}
#
#
#
SOURCE_TXT1="Please specify the installation Source:\n\n    1) NFS\n    2) SAMBA\n    3) FTP\n    0) Abort\n\nChoice: "
IP_TXT1="Please enter the IP-Number of the host providing the installation media: "
IP_SERVER_TXT1="Please enter the IP-Number of the host running the X-Server: "
IP_ERROR1="\n Host is not reponding. please enter a new number\n"
DIR_TXT1="Please enter the directory of the installation media: "
ASK_VALID="Is the following correct?\\\n\\\n    Installation Source:  \$INST_INFO\\\n    IP-Address:           \$INST_IP_ADDR\\\n    Directory:            \$INST_IP_DIR\\\n\\\nYes/No: "
SCREEN_TXT1="Which terminal do want to use?\n\n    1) X-Window\n    2) VNC (VNC-Client or Java enabled Browser)\n    3) ssh\n    Choice: "
MOUNT_ERR="CD not mounted. Please check parameters."
ENTER_YES_NO="Please enter yes or no."
FTPUSERTXT="Please enter the username for the FTP-access (for anonymous just press enter): "
FTPPASSWORDTXT="Please enter the password for the FTP-Access (for anonymous just press enter): "
FTP_ERR="FTP-Server or directory not acessable. Please check parameters."
SMBUSERTXT="Please enter the username for the SMB-access (for guest just press enter): "
SMBPASSWORDTXT="Please enter the password for the SMB-Access (for guest just press enter): "
WORKDOMAINTXT="Please enter the Domain (for no domain just press enter): "
FTP_ASK_VALID="Is the following correct?\\\n\\\n    FTP User:  \$FTPUSER\\\n    FTP Password:           \$FTPPASSWORD\\\n\\\nYes/No: "
SMB_ASK_VALID="Is the following correct?\\\n\\\n    SMB User:  \$FTPUSER\\\n    SMB Password:           \$FTPPASSWORD\\\n    Domain:   \$WORKDOMAIN\\\n\\\nYes/No: "
VNC_PASSWORD_TXT="Please enter the Password for VNC-Access (6 to 8 characters): "
VNC_PASSWORD_ERROR="Passwort is too short. Please enter a new one.\n"
#
# checks an IP to have numbers only between 0 and 255:
#
# example:
# if echo $IP_ADDR | check_ip; then ...
#
function check_ip()
{
        IFS=". " read ip1 ip2 ip3 ip4 rest
        for i in ip1 ip2 ip3 ip4
        do
                eval x=\$$i
		[ "$x" = "" ] && return 1
                if [ "$x" -lt 0 -o "$x" -gt 255 ]; then
                        echo "$x: Value must be between 0 and 255"
                        return 1
                fi
        done
        return 0
}
#
#
#
ask_source()
{
#
while :
do
   echo -en $SOURCE_TXT1
   source=$INST_INFO
   [ "$INST_INFO" = "nothing" ] && read source
   case $source in
	1|nfs) INST_INFO=nfs ; break ;;
	2|SAMBA) INST_INFO=SAMBA ; break ;;
	3|ftp) INST_INFO=ftp ; break ;;
	0) INST_INFO=ABORT ; break ;;
	*) ;;
   esac
   INST_INFO="nothing"
done
#
} # ask_source
#
#
# yes_no reads either a yes or a no into $ANSW
#
function yes_no () {
  while :; do
    read ANSW
    case "$ANSW" in
      [yY] | [yY][eE][sS]) ANSW=yes
                     break;;
      [nN] | [nN][oO])  ANSW=no
                     break;;
    esac
    echo $ENTER_YES_NO
  done
}
#
#	Ask for the IP-Number of the server for nfs/samba/ftp/http
#
ask_ip()
{
while :
do
	echo -en $IP_TXT1
	ip=$INST_IP_ADDR
	[ "$INST_IP_ADDR" = "250.250.250.250" ] && read ip
	[ "$ip" = "" ] && continue
	if echo $ip | check_ip
	then
		INST_IP_ADDR=$ip
		$CONDOM ping -w 10 -n -c 3 $INST_IP_ADDR
		[ $? -eq 0 ] && break
		echo -en $IP_ERROR1
	fi
done
} # ask_ip
#
#	Ask for the IP-Number of the X-server
#
ask_ip_server()
{
while :
do
	echo -en $IP_SERVER_TXT1
	ip=$INST_X_ADDR
	[ "$INST_X_ADDR" = "251.251.251.251" ] && read ip
	[ "$ip" = "" ] && continue
	if echo $ip | check_ip
	then
		INST_X_ADDR=$ip
		$CONDOM ping -w 10 -n -c 3 $INST_X_ADDR
		[ $? -eq 0 ] && break
		echo -en $IP_ERROR1
	fi
done
} # ask_ip_server
#
#	Ask for the directory of the install image
#
ask_dir()
{
while :
do
	echo -en $DIR_TXT1
	[ "$INST_IP_DIR" = "empty" ] && read INST_IP_DIR
	[ -z "$INST_IP_DIR" ] && continue
	if `echo $INST_IP_DIR | grep -v "^/" > /dev/null`
	then
		INST_IP_DIR=/$INST_IP_DIR
	fi
	break;
done
} # ask_dir
#
#
#
ask_screen()
{
while :
do
	echo -en $SCREEN_TXT1
	[ "$INST_SCREEN" = "nothing" ] && read INST_SCREEN
	case $INST_SCREEN in
		1|X) INST_SCREEN=X
		   break
		;;
		2|VNC) INST_SCREEN=VNC
		   while :
		   do
			   echo -en $VNC_PASSWORD_TXT
			   [ "$VNC_PASSWORD" = "1234" ] && read VNC_PASSWORD
			   [ ${#VNC_PASSWORD} -gt 5 ] && break
			   echo -en $VNC_PASSWORD_ERROR
			   VNC_PASSWORD="1234"
		   done
		   break
		;;
		3|SSH) INST_SCREEN=SSH
		   break
		;;
		*)
		;;
	esac
done
} # ask_screen
#
#	Installation via NFS
#
nfs_install()
{
#
#	Mount filesystems and start yast
#
$CONDOM mount -t nfs $INST_IP_ADDR:$INST_IP_DIR /var/adm/mount -o ro
if [ ! \( -d /var/adm/mount/boot -o -d /var/adm/mount/CD1/boot \) -a -z "$CONDOM" ]
then
	echo $MOUNT_ERR
	NO_ERROR=no
	return 0
fi
umount /var/adm/mount
return 1
}
#
#	Installation via SAMBA
#
samba_install()
{
#
#     Ask for domain/username/PW
#
while :
do
	echo -en $SMBUSERTXT
	FTPUSER=$SAMBAUSER
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || read FTPUSER
#	[ -z "$FTPUSER" ] && continue
	echo -en $SMBPASSWORDTXT
	FTPPASSWORD=$SAMBAPASSWORD
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || read FTPPASSWORD
#	[ -z "$FTPPASSWORD" ] && continue
	echo -en $WORKDOMAINTXT
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || read WORKDOMAIN
#	[ -z "$WORKDOMAIN" ] && continue
	eval echo -en $SMB_ASK_VALID
	ANSW=yes
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || yes_no
	[ "$ANSW" = "yes" ] && break
done
#
#	Mount filesystems and start yast
#
# $CONDOM mount -t smbfs //$INST_IP_ADDR/$INST_IP_DIR /var/adm/mount -o ro
# if [ ! \( -d /var/adm/mount/boot -o -d /var/adm/mount/CD1/boot \) -a -z "$CONDOM" ]
# then
	# echo $MOUNT_ERR
	# return 0
# fi
# umount /var/adm/mount
return 1
}
#
#	Installation via FTP
#
ftp_install()
{
while :
do
	echo -en $FTPUSERTXT
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || read FTPUSER
#	[ -z "$FTPUSER" ] && continue
	echo -en $FTPPASSWORDTXT
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || rread FTPPASSWORD
#	[ -z "$FTPPASSWORD" ] && continue
	eval echo -en $FTP_ASK_VALID
	ANSW=yes
	[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || yes_no
	[ ! "$ANSW" = "yes" ] && continue
	IP_FTP_USER=$FTPUSER
	IP_FTP_PASSWORD=$FTPPASSWORD
	[ -z "$IP_FTP_USER" ] && IP_FTP_USER=anonymous
	[ -z "$IP_FTP_PASSWORD" ] && IP_FTP_PASSWORD=bla_fasel
#
	NETRC=/tmp/.netrc
	HOME=/tmp
#
	echo "machine $INST_IP_ADDR" > $NETRC
	echo "login $IP_FTP_USER" >> $NETRC
	echo "password $IP_FTP_PASSWORD" >> $NETRC
#
	ftp  <<EOF 2>&1 > /dev/null
open $INST_IP_ADDR
cd $INST_IP_DIR
get content /tmp/content
quit
EOF
	if [ -f /tmp/content ]
	then
		rm /tmp/content
		break
	else
		echo $FTP_ERR
		NO_ERROR=no
		return 0
	fi
done
return 1
}
#
#	Write /etc/install.inf and /etc/netsetup.inf
#
write_info_file()
{
#	SetupNetIf: 0 prevents linuxrc from configuring the interface
	echo -en "Language: en_US\nKeytable: us\nSetupNetIF: 0\nTextmode: 0\nManual: 0\n" > $INFOFILENAME
	grep "^IP:"  $NETSETUPFILE >> $INFOFILENAME
	grep "^Gateway:"  $NETSETUPFILE >> $INFOFILENAME
	grep "^Nameserver:"  $NETSETUPFILE >> $INFOFILENAME
	grep "^Machinename:"  $NETSETUPFILE | sed -e "s/Machinename/Hostname/">> $INFOFILENAME
	grep "^Netmask:"  $NETSETUPFILE >> $INFOFILENAME
	echo "Server: $INST_IP_ADDR" >> $INFOFILENAME
	echo "Serverdir: $INST_IP_DIR" >> $INFOFILENAME
	echo "Instmode: $INST_INFO" >> $INFOFILENAME
	[ "$INST_INFO" = "ftp" ] && echo "Install: ftp://$INST_IP_ADDR$INST_IP_DIR" >> $INFOFILENAME
	[ "$INST_INFO" = "SAMBA" ] && echo "Install: smb://$INST_IP_ADDR$INST_IP_DIR" >> $INFOFILENAME
	[ ! -z "$FTPUSER" ] && echo "Username: $FTPUSER" >> $INFOFILENAME
	[ ! -z "$FTPPASSWORD" ] && echo "Password: $FTPPASSWORD" >> $INFOFILENAME
	[ ! -z "$WORKDOMAIN" ] && echo "WorkDomain: $WORKDOMAIN" >> $INFOFILENAME
	case $INST_SCREEN in
		X)
			echo "Display_IP: $INST_X_ADDR" >> $INFOFILENAME
			echo "Display_IP: $INST_X_ADDR" >> $NETSETUPFILE
		;;
		VNC)
			echo "VNC: 1" >> $INFOFILENAME
			echo "VNCPassword: $VNC_PASSWORD" >> $INFOFILENAME
		;;
		SSH)
			echo "UseSSH: 1" >> $NETSETUPFILE
#
#			Setting console to this value
#			means, that yast is asking for the terminaltype
#
			echo "Console: ttyS0,9600" >> $NETSETUPFILE
		;;
		*)
		;;
	esac
} # write_info_file
#
#	MAIN
#
if [ ! -z "$CONDOM" ]
then
	INFOFILENAME="./info.txt"
	NETSETUPFILE="./netsetup.inf"
else
	INFOFILENAME="/info"
	NETSETUPFILE="/etc/netsetup.inf"
fi
#
#
#
NO_ERROR=yes
	while :
	do
		ask_source
		echo
		[ "$INST_INFO" = ABORT ] && break
#		echo $INST_INFO
#
		ask_ip
		echo
#		echo $INST_IP_ADDR
#
		ask_dir
		echo
#		echo $INST_IP_DIR

		eval echo -en $ASK_VALID
		ANSW=yes
		[ "$AUTOINSTALL" = "yes" -a "$NO_ERROR" = "yes" ] || yes_no
		[ "$ANSW" = "no" ] && continue
#
#		Parameters are valid
#		Get the source
#
		case $INST_INFO in
			nfs)
				nfs_install || break
			;;
			SAMBA)
				samba_install || break
			;;
			ftp)
				ftp_install || break;
			;;
			*)
			;;
		esac
		NO_ERROR=no
	done
#
#	Filesystem and files are ready
#	Ask the user for VNC or X-Windows
#
	while :
	do
#
#		Ask what to use: X, VNC or ssh
#
		ask_screen
		echo
		if [ "$INST_SCREEN" = "X" ]
		then
#
#			We use X-Windows. Ask for IP-Number of Server
#
			ask_ip_server
			echo
		fi
#		export INSTSYS=/var/adm/mnt
		case $INST_SCREEN in
			X)
				export DISPLAY=$INST_X_ADDR:0.0
				break
			;;
			VNC)
				export VNC=1
				break
			;;
			SSH)
				break
			;;
			*)
			;;
		esac
	done
#
#
#
if [ "$INST_INFO" != "ABORT" ]
then
#
	write_info_file
#
#	kill portmap (#18461)
#
for i in /proc/[0-9]*
do
	grep -s portmap $i/cmdline > /dev/null
	if [ $? = 0 ]
	then
		OLDIFS=$IFS
		IFS="/$OLDIFS"
		set -- $i
		IFS=$OLDIFS
		kill $3
	fi
done
#
#	Start linuxrc
#
$CONDOM /bin/linuxrc
#
	[ ! -z "$CONDOM" ] && set
fi
:
