#!/bin/bash
echo 'This is SuSE Instsys Version %{version} Rel. %{release}'
echo 'Build date: Tue Aug  7 14:49:34 CEST 2001'
PATH=/sbin:/bin:/usr/sbin:/usr/bin
#
#
#
set -x
chmod +x /linuxrc
function movetotmpfs
{
    mkdir newroot
    mount -t shm -onr_inodes=10240 shmfs /newroot
    cp -ax / newroot
    cd newroot
    mv newroot oldroot
    pivot_root . oldroot
    exec chroot . /linuxrc <dev/console >dev/console 2>&1
}
if test -d oldroot
then
    umount /oldroot
    freeramdisk /dev/ram0
    mv oldroot oldroot.old
elif test \! -d oldroot.old
then
    movetotmpfs
fi

echo done doing movetotmpfs
#
#
#
DIRS="/mounts /dev/pts /var/empty /var/adm/mnt /var/adm/mount"
for i in $DIRS
do
	[ ! -d $i ] && mkdir $i
done
#
#	Main
#

mount -t devpts devpts /dev/pts
. /bin/netsetup

cat /etc/netsetup.inf
echo Next step 
read muell
#
#	Ask for Installation source & start yast
#
. /inst_source
#
#
#
dmesg > /kernel.msg
echo "
You should be able to login via telnet/ssh now.
To restart network setup, enter:

netsetup
"
while bash -login
do echo "linuxrc $$: restarting bash"; sleep 1; done
