#!/bin/bash
echo 'This is SuSE Instsys Version %{version} Rel. %{release}'
echo 'Build date: Thu Jul 25 15:12:53 CEST 2002'
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
#
#
#
chmod +x /linuxrc
function movetotmpfs
{
    mkdir newroot
    mount -t shm -onr_inodes=10240 shmfs /newroot
    cp -ax / newroot
    cd newroot
    mv newroot oldroot.old
    pivot_root . oldroot.old
    exec chroot . /linuxrc <dev/console >dev/console 2>&1
}
if test -d oldroot.old
then
    umount /oldroot.old
    freeramdisk /dev/ram0
    mv oldroot.old oldroot
elif test \! -d oldroot
then
    movetotmpfs
fi

echo done doing movetotmpfs
#
#
#
/usr/sbin/groupadd -g 65 -o -r sshd
/usr/sbin/useradd -o -g sshd -u 71 -s /bin/false -c "SSH daemon" -d /var/lib/sshd sshd
#
#
DIRS="/mounts /dev/pts /var/empty /var/adm/mnt /var/adm/mount /var/log/YaST2"
for i in $DIRS
do
	[ ! -d $i ] && mkdir $i
done
[ -d /var/log/YaST2 ] && {
for i in  "y2log y2log-1 y2log-2 y2log-3 y2log-4 y2start.log"
do
	touch /var/log/YaST2/$i
done
}
#
#	Main
#
mount -t devpts devpts /dev/pts

. /bin/netsetup

# cat /etc/netsetup.inf
# echo Next step 
# read muell
#
#	Ask for Installation source & start yast
#
# . /inst_source
#
#
#
dmesg > /kernel.msg
echo "
You should be able to login via telnet/ssh now.
To restart network setup, enter:

netsetup
"
while bash -login
do echo "linuxrc $$: restarting bash"; sleep 1; done
