#! /usr/bin/perl

# helper script that
#
# (1) writes a list of assigned IP adresses to STDOUT, and
#
# (2) writes the FQDN or, if not available, the first IP to STDERR
#
# The address in (2) should be something we can be reached by via network.

$up = 0;

for (`wicked show all 2>/dev/null`) {
  chomp;
  if(/^(\S+)\s*(\S+)/) {
    $up = $1 ne 'lo' && $2 eq 'up';
    next;
  }
  next unless $up;

  if(/^\s+addr:\s+ipv\S+\s+(\S+)/) {
    $addr = $1;
    $addr =~ s#/.*$##;
    push @addr, $addr;
  }
}

if(@addr) {
  chomp ($host = `hostname -f 2>/dev/null`);
  $host = $addr[0] if $host !~ /\./;

  print STDERR "$host\n";

  print "IP addresses:\n";
  print "  $_\n" for @addr;
}

