#! /usr/bin/perl

# helper script that
#
# (1) writes a list of assigned IP adresses to ARG1, and
#
# (2) writes the FQDN or, if not available, the first IP to ARG2
#
# The address in (2) should be something we can be reached by via network.
#
# usage:
#
# hostip_from_wicked ARG1 ARG2

$up = 0;

for (`wicked show all 2>/dev/null`) {
  chomp;
  if(/^(\S+)\s*(\S+)/) {
    $up = $1 ne 'lo' && $2 eq 'up';
    next;
  }
  next unless $up;

  if(/^\s+addr:\s+ipv\S+\s+(\S+)/) {
    $addr = $1;
    $addr =~ s#/.*$##;
    push @addr, $addr;
  }
}

if(@addr) {
  chomp ($host = `hostname -f 2>/dev/null`);
  $host = $addr[0] if $host !~ /\./;

  if($ARGV[0] && open $f, ">$ARGV[0]") {
    print $f "IP addresses:\n";
    print $f "  $_\n" for @addr;
    close $f;
  }

  if($ARGV[1] && open $f, ">$ARGV[1]") {
    print $f "$host\n";
    close $f;
  }
}

