#! /usr/bin/perl

# make all locales links to en_US, cs_CZ or ru_RU
# according to the needed iso...

@real_locales = qw (
  en_US/ISO-8859-1
  en_US.UTF-8/UTF-8
  cs_CZ/ISO-8859-2
  ru_RU.KOI8-R/KOI8-R
);

die "no locale archive\n" unless -f "/usr/lib/locale/locale-archive";

system "mkdir -p /tmp/usr/lib/locale";
system "rm -f /tmp/usr/lib/locale/locale-archive";

for (@real_locales) {
  @l = split /\//;
  die "oops, wrong locale data" unless @l == 2;
  $l = $l[0];
  $l =~ s/\..*$//;
  print "localedef --prefix=/tmp -c -i $l -f $l[1] $l[0]\n";
  die "oops, locale build failed" if system "localedef --prefix=/tmp -c -i $l -f $l[1] $l[0]";
}

chomp(@l = `localedef --prefix=/tmp --list-archive`);
@real_locales{@l} = ();
chomp %real_locales;

chomp(@l = `localedef --list-archive`);
@all_locales{@l} = ();
chomp %my_locales;

for (sort keys %real_locales) {
  print "$_\n";
}

for (sort keys %all_locales) {
  if(!$real_locales{$_}) {
    if(/\.utf8$/) {
      push @aliases, "$_\ten_US.utf8\n";
    }
    else {
      if(/^(hr_HR|hu_HU|ro_RO|sk_SK|sl_SI|pl_PL)/) {
        push @aliases, "$_\tcs_CZ\n";
      }
      else {
        push @aliases, "$_\ten_US\n";
      }
    }
  }
}

open F, ">/tmp/locale.alias";
print F @aliases;
close F;

