#! /usr/bin/perl

# link everything to en_US.utf8

$tmp_locale = "tmp/locale";

system "rm -rf $tmp_locale";
mkdir $tmp_locale, 0755;
system "cp -a usr/lib/locale/en_US.utf8 $tmp_locale";

for (<usr/lib/locale/*>) {
  s#^.*/##;
  symlink "en_US.utf8", "$tmp_locale/$_";
  if(!/@/) {
    s#\..*$##;
    $_ .= ".utf8";
    symlink "en_US.utf8", "$tmp_locale/$_";
  }
}

