#! /bin/sh

dst=$1
theme=$2
cfg=$3
spl=$4

splash -s -f /etc/bootsplash/themes/$theme/config/bootsplash-$cfg.cfg >/$dst/$spl.spl
splash -s -c -f /etc/bootsplash/themes/$theme/config/bootsplash-$cfg.cfg | gzip -9c >/$dst/gz/$spl.spl

cp -a /etc/bootsplash/themes/$theme/animations /$dst
cp -a /etc/bootsplash/themes/$theme/images /$dst
rm -f /$dst/images/*-*.jpg

mkdir xxx
cp -a --parents /etc/bootsplash/themes/$theme/config/*-$cfg.* xxx
cp -a --parents /etc/bootsplash/themes/$theme/images/*-$cfg.* xxx
ln -s /etc/bootsplash/themes/$theme/config/bootsplash-$cfg.cfg xxx/etc/splash.cfg
cd xxx
chmod -R a+rX .
find | cpio --quiet -o -H newc | gzip -9 >>/$dst/gz/$spl.spl
cd /
rm -r xxx

