#! /usr/bin/perl

while(<>) {
  push @t, $1 if /^yast2-trans-(\S+)/;
}

open F, ">yast2-trans.inc";
print F "yast2-trans-$_:\n  /\n" for (@t);
close F;

open F, ">yast2-trans.list";
print F join(' ', @t), "\n";
close F;

